ignore:
  - tests/**/*
  - piquasso/_math/hafnian/*
  - piquasso/_math/permanent.py
  - piquasso/_simulators/fock/pure/calculations/homodyne.py
  - piquasso/_math/combinatorics.py
  - piquasso/_math/fock.py
  - piquasso/_math/indices.py
  - piquasso/_simulators/fock/calculations.py
  - piquasso/_simulators/connectors/numpy_/interferometer.py
