ignore:
  - tests/**/*
  - piquasso/_math/hafnian/*
  - piquasso/_math/permanent.py
  - piquasso/_simulators/fock/pure/calculations/homodyne.py
  - piquasso/_math/combinatorics.py
  - piquasso/_math/fock.py
  - piquasso/_math/indices.py
  - piquasso/_math/transformations.py
  - piquasso/_simulators/fock/calculations.py
  - piquasso/_simulators/connectors/connections.py
  - piquasso/_simulators/connectors/_utils.py
  - piquasso/_simulators/connectors/numpy_/interferometer.py
  - piquasso/_simulators/connectors/numpy_/connections.py
  - piquasso/fermionic/_utils.py
