name: Build wheels

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # macos-13 is an intel runner, macos-14 is apple silicon
        os: [macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.20.0
        env:
          CIBW_TEST_EXTRAS: "tensorflow,jax"
          CIBW_TEST_REQUIRES: pytest
          # NOTE: --import-mode=importlib prevents pytest to import piquasso from
          # directory
          CIBW_TEST_COMMAND: "pytest -v --import-mode=importlib {project}/tests"

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
